-- ClipHutch license schema for Cloudflare D1
--
-- A license is keyed by its CH-XXXX-XXXX-XXXX-XXXX string. Each license is
-- linked to a single Stripe Checkout Session at issuance time and is allowed
-- up to MAX_DEVICES_PER_LICENSE distinct activations.

CREATE TABLE IF NOT EXISTS licenses (
  key                 TEXT PRIMARY KEY,
  email               TEXT NOT NULL,
  stripe_session_id   TEXT NOT NULL UNIQUE,
  payment_intent_id   TEXT,
  product             TEXT NOT NULL DEFAULT 'cliphutch', -- 'cliphutch' | 'computedkit'
  status              TEXT NOT NULL DEFAULT 'active',  -- 'active' | 'refunded' | 'revoked'
  created_at          INTEGER NOT NULL,                -- ms since epoch
  refunded_at         INTEGER
);

CREATE INDEX IF NOT EXISTS idx_licenses_email ON licenses(email);
CREATE INDEX IF NOT EXISTS idx_licenses_payment_intent ON licenses(payment_intent_id);
CREATE INDEX IF NOT EXISTS idx_licenses_product ON licenses(product);

CREATE TABLE IF NOT EXISTS activations (
  license_key         TEXT NOT NULL,
  installation_id     TEXT NOT NULL,                   -- UUID generated by extension on first activation
  activated_at        INTEGER NOT NULL,                -- ms since epoch
  last_seen_at        INTEGER NOT NULL,                -- ms since epoch, updated on each /validate call
  PRIMARY KEY (license_key, installation_id),
  FOREIGN KEY (license_key) REFERENCES licenses(key) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_activations_license ON activations(license_key);
