-- ClipHutch license schema for Cloudflare D1
--
-- A license is keyed by its CH-XXXX-XXXX-XXXX-XXXX string. Each license is
-- linked to a single Stripe Checkout Session at issuance time and is allowed
-- up to MAX_DEVICES_PER_LICENSE distinct activations.

CREATE TABLE IF NOT EXISTS licenses (
  key                 TEXT PRIMARY KEY,
  email               TEXT NOT NULL,
  stripe_session_id   TEXT NOT NULL UNIQUE,
  payment_intent_id   TEXT,
  product             TEXT NOT NULL DEFAULT 'cliphutch', -- 'cliphutch' | 'computedkit'
  status              TEXT NOT NULL DEFAULT 'active',  -- 'active' | 'refunded' | 'revoked'
  created_at          INTEGER NOT NULL,                -- ms since epoch
  refunded_at         INTEGER,
  refunded_event_id   TEXT,
  refund_amount       INTEGER,
  refund_amount_refunded INTEGER,
  email_sent_at       INTEGER,                         -- ms since epoch; NULL until the license email is delivered
  email_delivery_key  TEXT,
  email_delivery_claimed_at INTEGER
);

CREATE INDEX IF NOT EXISTS idx_licenses_email ON licenses(email);
CREATE INDEX IF NOT EXISTS idx_licenses_payment_intent ON licenses(payment_intent_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_licenses_payment_intent_unique
  ON licenses(payment_intent_id) WHERE payment_intent_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_licenses_product ON licenses(product);

CREATE TABLE IF NOT EXISTS activations (
  license_key         TEXT NOT NULL,
  installation_id     TEXT NOT NULL,                   -- UUID generated by extension on first activation
  activated_at        INTEGER NOT NULL,                -- ms since epoch
  last_seen_at        INTEGER NOT NULL,                -- ms since epoch, updated on each /validate call
  created_event_id    TEXT,
  PRIMARY KEY (license_key, installation_id),
  FOREIGN KEY (license_key) REFERENCES licenses(key) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_activations_license ON activations(license_key);

-- Append-only, metadata-minimized correlation for row-level repair. Raw
-- license keys, installation IDs, emails, and Stripe payloads never belong in
-- this table; the Worker stores SHA-256 fingerprints instead.
CREATE TABLE IF NOT EXISTS license_mutation_journal (
  id                       INTEGER PRIMARY KEY AUTOINCREMENT,
  source                   TEXT NOT NULL,
  external_event_id        TEXT NOT NULL,
  license_fingerprint      TEXT NOT NULL,
  installation_fingerprint TEXT,
  mutation_type            TEXT NOT NULL,
  previous_state           TEXT,
  next_state               TEXT,
  occurred_at              INTEGER NOT NULL,
  expires_at               INTEGER NOT NULL,
  metadata_json            TEXT NOT NULL DEFAULT '{}',
  UNIQUE (source, external_event_id, mutation_type)
);

CREATE INDEX IF NOT EXISTS idx_license_mutation_journal_license
  ON license_mutation_journal(license_fingerprint, occurred_at);
CREATE INDEX IF NOT EXISTS idx_license_mutation_journal_expiry
  ON license_mutation_journal(expires_at);

CREATE TABLE IF NOT EXISTS stripe_refund_events (
  event_id          TEXT PRIMARY KEY,
  payment_intent_id TEXT NOT NULL,
  is_full           INTEGER NOT NULL CHECK (is_full IN (0, 1)),
  amount            INTEGER NOT NULL,
  amount_refunded   INTEGER NOT NULL,
  observed_at       INTEGER NOT NULL,
  applied_at        INTEGER,
  expires_at        INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_stripe_refund_events_payment_intent
  ON stripe_refund_events(payment_intent_id, is_full, applied_at);
CREATE INDEX IF NOT EXISTS idx_stripe_refund_events_expiry
  ON stripe_refund_events(expires_at);

CREATE TABLE IF NOT EXISTS activation_tombstones (
  operation_id      TEXT PRIMARY KEY,
  license_fingerprint TEXT NOT NULL,
  installation_fingerprint TEXT NOT NULL,
  activation_id     TEXT NOT NULL,
  deactivated_at    INTEGER NOT NULL,
  reactivated_at    INTEGER
);

CREATE INDEX IF NOT EXISTS idx_activation_tombstones_pair
  ON activation_tombstones(
    license_fingerprint, installation_fingerprint, reactivated_at
  );
